FROM ghcr.io/sdr-enthusiasts/browser-screenshot-service:latest

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN set -x && \
    # install packages needed for testing
    apt-get update && \
    apt-get install -y imagemagick sharutils gridsite-clients && \
    # make output dir
    mkdir -p /output && \
    # start server in the background
    nohup bash -c "timeout 60s ./snapapi.py &" && \
    # wait for server to start
    sleep 5 && \
    # attempt a snapshot
    curl \
        -o /output/out.png \
        --silent \
        http://127.0.0.1:5042/snap/ADFDF8 \
        && \
    # check image generated is actually a PNG
    identify /output/out.png && \
    # uuencode output
    uuencode -m /output/out.png - > /output/out.png.uuencoded.base64 && \
    # upload image (the sed puts all of the uuencoded output on one line, so it goes into the variable)
    echo ::set-output name=output_image::"$(sed -z 's/\n/,/g;s/,$/\n/' /output/out.png.uuencoded.base64)"
